### ISSUE TITLE
Map Editor Zoom problems

### ISSUE THREAD

**Issue by rygos** [EasyRPG/Editor#145]
Hi,
the biggest zoom for me is 200% but this is very small on my retina screen. 

200% Zoom:
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/1985803/93821365-bf032080-fc5e-11ea-8127-78fe53b872a9.png">

100% Zoom:
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/1985803/93821398-cc200f80-fc5e-11ea-8078-d9182dd3fdfc.png">

If I try to zoom smaller than 100% the editor crashes. The fist time I try this I get a error message but only on the first try. I can't reproduce the error message anymore =(

**Comment by Ghabry** [comment]
The error is a floating point exception. Div/0. Saw this also few days ago.

**Comment by gadesx** [comment]
I think that the best is made like some emulators function, show max size with integer scaling.
That could works fine to see maps with monitors of 1080p, 4k, even 8k resolutions

Smaller than 100% or values like 125% are uneven pixels, isn't the best to draw perfect pixel maps

**Comment by rueter37** [comment]
The division of 0 is caused by the casting of `m_scale` in [map_scene.cpp](https://github.com/EasyRPG/Editor/blob/master/src/ui/map/map_scene.cpp) to an integer. If the zoom level is below 100%, the `m_scale` value is 0 because of the casting and triggers the crash.

The minimum zoom level is 25% and the maximum zoom level is 200% at the moment. I would suggest to add the zoom levels 12.5% (useful to get a quick overview of large maps), 400% and 800% (useful for high resolution displays).
